// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using oai_poc_backend.Database;

#nullable disable

namespace oai_poc_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("oai_poc_backend.Models.OptionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("OptionCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8SsbiKhqQjjlndxJfA_Vq0EiCtLCKNQvfFw&s",
                            Name = "Style"
                        });
                });

            modelBuilder.Entity("oai_poc_backend.Models.OptionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("DetailedDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detailed_description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("OptionCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("option_category_id");

                    b.Property<int>("TokenValue")
                        .HasColumnType("int")
                        .HasColumnName("token_value");

                    b.HasKey("Id");

                    b.HasIndex("OptionCategoryId");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            DetailedDescription = "Create an image with simplified, exaggerated features, bold outlines, and vibrant colors. Characters should have expressive faces and dynamic poses, with a playful and whimsical aesthetic",
                            ImageUrl = "https://i.pinimg.com/564x/13/95/9a/13959adfbc9c48213e74ee6e0dc4f519.jpg",
                            Name = "Cartoon",
                            OptionCategoryId = 1,
                            TokenValue = 150
                        },
                        new
                        {
                            Id = 2,
                            Active = false,
                            DetailedDescription = "Anime style is characterized by vibrant colors, dynamic compositions, and expressive characters. Characters often have large, emotive eyes, distinct hairstyles, and exaggerated facial expressions. Backgrounds are detailed, featuring fantastical landscapes or urban settings. The style ranges from cute and whimsical (Chibi) to dark and realistic (Seinen). Common themes include adventure, romance, and the supernatural, depicted with a sense of motion and energy.",
                            ImageUrl = "https://img.freepik.com/premium-vector/vector-young-man-anime-style-character-vector-illustration-design-manga-anime-boy_147933-12395.jpg",
                            Name = "Anime",
                            OptionCategoryId = 1,
                            TokenValue = 150
                        });
                });

            modelBuilder.Entity("oai_poc_backend.Models.OrganizationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<long>("OrganizationNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_number");

                    b.HasKey("Id");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nocco AB",
                            OrganizationNumber = 5569426710L
                        },
                        new
                        {
                            Id = 2,
                            Name = "Panduro Hobby Aktiebolag",
                            OrganizationNumber = 5560736356L
                        });
                });

            modelBuilder.Entity("oai_poc_backend.Models.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AIModelUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ai_model_url");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<int>("TokenValue")
                        .HasColumnType("int")
                        .HasColumnName("token_value");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AIModelUrl = "https://tyngre.centracdn.net/client/dynamic/images/634_ed258f9eaf-se_tyngre_blueraspberry_240821_produktbild_1000x1340-08-full.jpg",
                            Created = new DateTime(2024, 10, 3, 16, 0, 5, 606, DateTimeKind.Local).AddTicks(2940),
                            Description = "The image features a product from the brand Tyngre, specifically their Blue Raspberry flavored supplement. The packaging is a cylindrical container with a sleek and modern design. The primary color of the container is a deep blue, which is complemented by white and light blue accents. At the top of the container, the Tyngre logo is prominently displayed in bold white letters. Below the logo, the flavor “Blue Raspberry” is clearly indicated in a stylish font, also in white. The background of the label features a subtle gradient from dark blue at the top to a lighter blue at the bottom, giving it a dynamic and appealing look.\r\n\r\nThe container also includes additional text and branding elements, such as nutritional information and product benefits, which are written in smaller fonts and positioned around the main logo and flavor text. The overall design is clean and visually appealing, aimed at attracting fitness enthusiasts and individuals looking for high-quality nutritional supplements.\r\n\r\nThe image is well-lit, highlighting the glossy finish of the container and making the colors pop. The product is centered in the frame, with no other objects or distractions in the background, ensuring that the focus remains solely on the supplement container.",
                            Name = "Blue Raspberry",
                            OrganizationId = 1,
                            TokenValue = 200
                        },
                        new
                        {
                            Id = 2,
                            AIModelUrl = "https://tyngre.centracdn.net/client/dynamic/images/69_639bd80db9-se_nocco_single_1000x1340_green_apple_60png-20-full.jpg",
                            Created = new DateTime(2024, 10, 3, 16, 0, 5, 606, DateTimeKind.Local).AddTicks(2993),
                            Description = "The image features a Tyngre Green Apple supplement can. The can is cylindrical with a glossy finish and a modern design. The primary color is a vibrant green, complemented by white and light green accents. The Tyngre logo is prominently displayed at the top in bold white letters. Below the logo, the flavor “Green Apple” is clearly indicated in a stylish white font. The background of the label features a subtle gradient from dark green at the top to a lighter green at the bottom, giving it a dynamic and appealing look. Additional text and branding elements, such as nutritional information and product benefits, are written in smaller fonts around the main logo and flavor text. The can is well-lit, highlighting its glossy finish and making the colors pop. The product is centered in the frame, with no other objects or distractions in the background, ensuring the focus remains solely on the supplement can.",
                            Name = "Green Apple",
                            OrganizationId = 1,
                            TokenValue = 200
                        },
                        new
                        {
                            Id = 3,
                            AIModelUrl = "https://static.panduro.com/ArticleImages/565x565/320205_01.webp",
                            Created = new DateTime(2024, 10, 3, 16, 0, 5, 606, DateTimeKind.Local).AddTicks(2998),
                            Description = "The image features a skein of yarn from Panduro. The yarn is soft and fluffy, with a chunky texture that suggests it is likely a bulky weight yarn. The color is a vibrant, solid red, giving it a rich and warm appearance. The yarn is neatly wound into a skein, showcasing its thickness and the evenness of the fibers. The fibers appear to be smooth and slightly shiny, indicating a high-quality material, possibly a blend of wool and synthetic fibers. The label wrapped around the skein includes branding and product information, but the text is not clearly visible in the image. The overall presentation of the yarn is clean and appealing, making it suitable for cozy projects like scarves, hats, or blankets.",
                            Name = "Akrylgarn",
                            OrganizationId = 2,
                            TokenValue = 200
                        },
                        new
                        {
                            Id = 4,
                            AIModelUrl = "https://static.panduro.com/ArticleImages/565x565/517034_01.webp",
                            Created = new DateTime(2024, 10, 3, 16, 0, 5, 606, DateTimeKind.Local).AddTicks(3000),
                            Description = "The product is a flat acrylic paintbrush designed for hobby and craft use. It features a wide, flat brush head with synthetic bristles that are ideal for smooth and even application of acrylic paints. The bristles are densely packed and have a slight stiffness, providing good control and precision. The brush head is attached to a sturdy, silver-colored ferrule that securely holds the bristles in place. The handle is made of wood and is painted in a vibrant blue color. It has a smooth, glossy finish and is ergonomically shaped for a comfortable grip. The handle tapers slightly towards the end, making it easy to maneuver during painting. The overall length of the brush is approximately 32 cm, making it suitable for both detailed work and covering larger areas. This brush is perfect for artists and hobbyists looking for a reliable tool for their acrylic painting projects.",
                            Name = "Akrylgarn",
                            OrganizationId = 2,
                            TokenValue = 200
                        });
                });

            modelBuilder.Entity("oai_poc_backend.Models.PromptModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("created");

                    b.Property<string>("FreeText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("free_text");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int")
                        .HasColumnName("template_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("UserId");

                    b.ToTable("Prompts");
                });

            modelBuilder.Entity("oai_poc_backend.Models.PromptOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OptionId")
                        .HasColumnType("int")
                        .HasColumnName("option_id");

                    b.Property<int?>("PromptId")
                        .HasColumnType("int")
                        .HasColumnName("prompt_id");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int")
                        .HasColumnName("template_id");

                    b.HasKey("Id");

                    b.HasIndex("OptionId");

                    b.HasIndex("PromptId");

                    b.HasIndex("TemplateId");

                    b.ToTable("PromptOptions");
                });

            modelBuilder.Entity("oai_poc_backend.Models.PromptSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("PromptId")
                        .HasColumnType("int")
                        .HasColumnName("prompt_id");

                    b.Property<int>("SettingId")
                        .HasColumnType("int")
                        .HasColumnName("setting_id");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int")
                        .HasColumnName("template_id");

                    b.HasKey("Id");

                    b.HasIndex("PromptId");

                    b.HasIndex("SettingId");

                    b.HasIndex("TemplateId");

                    b.ToTable("PromptSettings");
                });

            modelBuilder.Entity("oai_poc_backend.Models.SettingCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("SettingCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://static.thenounproject.com/png/2221964-200.png",
                            Name = "Aspect Ratio"
                        });
                });

            modelBuilder.Entity("oai_poc_backend.Models.SettingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("SettingCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("setting_category_id");

                    b.HasKey("Id");

                    b.HasIndex("SettingCategoryId");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://cdn-icons-png.flaticon.com/512/3172/3172457.png",
                            Name = "16:9",
                            SettingCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVIGEIuRzfjOoqg1ITa7FRRY72TJZtgjU3TA&s",
                            Name = "4:3",
                            SettingCategoryId = 1
                        });
                });

            modelBuilder.Entity("oai_poc_backend.Models.StatusModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Received"
                        },
                        new
                        {
                            Id = 2,
                            Name = "In progress"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Completed"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Failed"
                        });
                });

            modelBuilder.Entity("oai_poc_backend.Models.TemplateModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("created");

                    b.Property<string>("FreeText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("free_text");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("oai_poc_backend.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.HasIndex("OrganizationId");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("oai_poc_backend.Models.OptionModel", b =>
                {
                    b.HasOne("oai_poc_backend.Models.OptionCategory", "OptionCategory")
                        .WithMany("Options")
                        .HasForeignKey("OptionCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptionCategory");
                });

            modelBuilder.Entity("oai_poc_backend.Models.ProductModel", b =>
                {
                    b.HasOne("oai_poc_backend.Models.OrganizationModel", "Organization")
                        .WithMany("Products")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("oai_poc_backend.Models.PromptModel", b =>
                {
                    b.HasOne("oai_poc_backend.Models.ProductModel", "Product")
                        .WithMany("Prompts")
                        .HasForeignKey("ProductId");

                    b.HasOne("oai_poc_backend.Models.StatusModel", "Status")
                        .WithMany("Prompts")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("oai_poc_backend.Models.TemplateModel", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId");

                    b.HasOne("oai_poc_backend.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Status");

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("oai_poc_backend.Models.PromptOption", b =>
                {
                    b.HasOne("oai_poc_backend.Models.OptionModel", "Option")
                        .WithMany()
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("oai_poc_backend.Models.PromptModel", "Prompt")
                        .WithMany("PromptOptions")
                        .HasForeignKey("PromptId");

                    b.HasOne("oai_poc_backend.Models.TemplateModel", "Template")
                        .WithMany("PromptOptions")
                        .HasForeignKey("TemplateId");

                    b.Navigation("Option");

                    b.Navigation("Prompt");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("oai_poc_backend.Models.PromptSetting", b =>
                {
                    b.HasOne("oai_poc_backend.Models.PromptModel", "Prompt")
                        .WithMany("PromptSettings")
                        .HasForeignKey("PromptId");

                    b.HasOne("oai_poc_backend.Models.SettingModel", "Setting")
                        .WithMany()
                        .HasForeignKey("SettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("oai_poc_backend.Models.TemplateModel", "Template")
                        .WithMany("PromptSettings")
                        .HasForeignKey("TemplateId");

                    b.Navigation("Prompt");

                    b.Navigation("Setting");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("oai_poc_backend.Models.SettingModel", b =>
                {
                    b.HasOne("oai_poc_backend.Models.SettingCategory", "SettingCategory")
                        .WithMany("Settings")
                        .HasForeignKey("SettingCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SettingCategory");
                });

            modelBuilder.Entity("oai_poc_backend.Models.TemplateModel", b =>
                {
                    b.HasOne("oai_poc_backend.Models.ProductModel", "Product")
                        .WithMany("Templates")
                        .HasForeignKey("ProductId");

                    b.HasOne("oai_poc_backend.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("oai_poc_backend.Models.ApplicationUser", b =>
                {
                    b.HasOne("oai_poc_backend.Models.OrganizationModel", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("oai_poc_backend.Models.OptionCategory", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("oai_poc_backend.Models.OrganizationModel", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("oai_poc_backend.Models.ProductModel", b =>
                {
                    b.Navigation("Prompts");

                    b.Navigation("Templates");
                });

            modelBuilder.Entity("oai_poc_backend.Models.PromptModel", b =>
                {
                    b.Navigation("PromptOptions");

                    b.Navigation("PromptSettings");
                });

            modelBuilder.Entity("oai_poc_backend.Models.SettingCategory", b =>
                {
                    b.Navigation("Settings");
                });

            modelBuilder.Entity("oai_poc_backend.Models.StatusModel", b =>
                {
                    b.Navigation("Prompts");
                });

            modelBuilder.Entity("oai_poc_backend.Models.TemplateModel", b =>
                {
                    b.Navigation("PromptOptions");

                    b.Navigation("PromptSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
